namespace FishMarket.Api.Services
{
    /// <summary>
    /// Email sending service.
    /// </summary>
    public interface IEmailSender
    {
        /// <summary>
        /// Sends a single email to our internal records.
        /// </summary>
        /// <param name="subject">The subject of your email.</param>
        /// <param name="plainTextContent">The text/plain content of the email body.</param>
        /// <returns>A <see cref="Task" /> representing the asynchronous operation.</returns>
        /// <exception cref="Exception">
        /// The method will NOT catch and swallow exceptions generated by sending a request through the internal HTTP client.
        /// Any underlying exception will pass right through. In particular, this means that you may expect a TimeoutException
        /// if you are not connected to the Internet.
        /// </exception>
        Task SendEmailAsync(string email, string subject, string plainTextContent);
    }
}