@password = <Password>
@file = <File Path>
@token = <JWT Token>

### Create a user
POST http://localhost:5169/users
Content-Type: application/json

{
    "email": "myuser@test.com",
    "password": "{{password}}"
}

### Get a token
POST http://localhost:5169/users/token
Content-Type: application/json

{
    "email": "myuser@test.com",
    "password": "{{password}}"
}

### Create a fish
POST http://localhost:5169/fishes
Authorization:  Bearer {{token}}
Content-Type: application/json

{
    "name": "Fish 1",
    "price": 10.5
}

### Update a fish
PUT http://localhost:5169/fishes/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": 2,
    "name": "Fish 2",
    "price": 20.5
}

### Upload a fish image
POST http://localhost:5169/fishes/2/image
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="{{file}}"
Content-Type: application/octet-stream

< {{file}}
--WebAppBoundary--

### Delete a fish
DELETE http://localhost:5169/fishes/2
Authorization: Bearer {{token}}
Content-Type: application/json

### Get all fishes
GET http://localhost:5169/fishes
Authorization: Bearer {{token}}
Content-Type: application/json

### Get a fish
GET http://localhost:5169/fishes/2
Authorization: Bearer {{token}}
Content-Type: application/json