### Create a user
@password = 123Mudar!

POST http://localhost:5169/users
Content-Type: application/json

{
    "email": "myuser@test.com",
    "password": "{{password}}"
}

### Get a token
POST http://localhost:5169/users/token
Content-Type: application/json

{
    "email": "myuser@test.com",
    "password": "{{password}}"
}